# Generated by Django 2.0.3 on 2018-10-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181013_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='name',
            new_name='nickname',
        ),
    ]
