# Generated by Django 2.0.3 on 2018-10-13 14:08

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181013_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
