# Generated by Django 2.0.3 on 2018-10-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181013_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('C', 'Chinese')], default='English', max_length=10),
        ),
    ]
