# Generated by Django 2.0.3 on 2018-10-17 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userinfo_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='language',
            field=models.CharField(choices=[('E', 'English'), ('C', '简体中文')], default='English', max_length=10),
        ),
    ]
