# Generated by Django 2.0.3 on 2018-10-20 09:26

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20181020_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(choices=[('M', 'Message'), ('I', 'Invitation')], default='Message', max_length=12),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=markdownx.models.MarkdownxField(max_length=2000),
        ),
    ]
