# Generated by Django 2.0.3 on 2018-11-10 10:45

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20181110_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile',
            field=imagekit.models.fields.ProcessedImageField(default='static/img/default.jpg', upload_to='user/img'),
        ),
    ]
