# Generated by Django 2.0.3 on 2018-11-20 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20181120_1058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='is_Read',
            new_name='is_read',
        ),
    ]
