# Generated by Django 2.0.3 on 2018-11-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-11-10 18:42:44.430493  Create diary'),
        ),
    ]
