# Generated by Django 2.0.3 on 2018-11-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0002_auto_20181118_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='<django.db.models.fields.DateTimeField>  Create diary'),
        ),
    ]
