# Generated by Django 2.0.3 on 2018-11-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0002_auto_20181110_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-11-10 18:45:37.394099  Create diary'),
        ),
    ]
