# Generated by Django 2.0.3 on 2018-11-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0003_auto_20181110_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-11-10 18:46:25.202217  Create diary'),
        ),
    ]
