# Generated by Django 2.0.3 on 2018-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0004_auto_20181110_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-11-11 15:21:23.163271  Create diary'),
        ),
    ]
