# Generated by Django 2.0.3 on 2018-11-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0005_auto_20181111_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-11-14 10:44:41.189194  Create diary'),
        ),
    ]
