# Generated by Django 2.0.3 on 2018-11-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lenotes', '0007_auto_20181114_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='diary_log',
            field=models.TextField(default='2018-11-18 19:53:44.231698  Create diary'),
        ),
    ]
