# Generated by Django 2.0.3 on 2018-11-10 02:34

from django.db import migrations
import simditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20181110_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=simditor.fields.RichTextField(),
        ),
    ]
