# Generated by Django 2.0.3 on 2018-12-19 17:02

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sonata', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Art_Comment',
            new_name='Idea',
        ),
        migrations.RenameModel(
            old_name='Art_Tag',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='tags',
            new_name='types',
        ),
    ]

    atomic = False
