# Generated by Django 2.0.3 on 2018-12-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20181118_2148'),
        ('sonata', '0002_auto_20181219_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='types',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='blog.Tag'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
